### ISSUE TITLE
Colored blocks in the background

### ISSUE THREAD

**Issue by ristoretto** [Bryan-Legend/fall-from-grace#8]

**Comment by Bryan-Legend** [comment]
I'm not going to work on cosmetics until we have some playable levels.

**Comment by Bryan-Legend** [comment]
![image](https://user-images.githubusercontent.com/920120/187086720-99877334-4159-4b32-accb-76fadf26443c.png)

**Comment by Bryan-Legend** [comment]
To use this setup your Tiled layers like this: 
![image](https://user-images.githubusercontent.com/920120/187086741-dd66a85d-0ff2-4d62-a82b-f98d73420d2e.png)
